/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/kylona/workspace/qbot/dds/HelloWorldData.h
  Source: /home/kylona/workspace/qbot/dds/HelloWorldData.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC__HOME_KYLONA_WORKSPACE_QBOT_DDS_HELLOWORLDDATA_H_116FB0DBB0D8A01665A1469C69210BEE
#define DDSC__HOME_KYLONA_WORKSPACE_QBOT_DDS_HELLOWORLDDATA_H_116FB0DBB0D8A01665A1469C69210BEE

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct qbot_msg_HelloWorldData
{
  int32_t user_id;
  char * message;
} qbot_msg_HelloWorldData;

extern const dds_topic_descriptor_t qbot_msg_HelloWorldData_desc;

#define qbot_msg_HelloWorldData__alloc() \
((qbot_msg_HelloWorldData*) dds_alloc (sizeof (qbot_msg_HelloWorldData)));

#define qbot_msg_HelloWorldData_free(d,o) \
dds_sample_free ((d), &qbot_msg_HelloWorldData_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_KYLONA_WORKSPACE_QBOT_DDS_HELLOWORLDDATA_H_116FB0DBB0D8A01665A1469C69210BEE */
