/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/kylona/workspace/qbot/dds/HelloWorldData.h
  Source: /home/kylona/workspace/qbot/dds/HelloWorldData.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC__HOME_KYLONA_WORKSPACE_QBOT_DDS_HELLOWORLDDATA_H_F8AF025354452DA7AB0CCD5A1F7C881C
#define DDSC__HOME_KYLONA_WORKSPACE_QBOT_DDS_HELLOWORLDDATA_H_F8AF025354452DA7AB0CCD5A1F7C881C

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct HelloWorldData_Msg
{
  int32_t userID;
  char * message;
} HelloWorldData_Msg;

extern const dds_topic_descriptor_t HelloWorldData_Msg_desc;

#define HelloWorldData_Msg__alloc() \
((HelloWorldData_Msg*) dds_alloc (sizeof (HelloWorldData_Msg)));

#define HelloWorldData_Msg_free(d,o) \
dds_sample_free ((d), &HelloWorldData_Msg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_KYLONA_WORKSPACE_QBOT_DDS_HELLOWORLDDATA_H_F8AF025354452DA7AB0CCD5A1F7C881C */
