/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/kylona/workspace/qbot/dds/HelloWorldData.h
  Source: /home/kylona/workspace/qbot/dds/HelloWorldData.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC__HOME_KYLONA_WORKSPACE_QBOT_DDS_HELLOWORLDDATA_H_1BAFEBD2278FF078A8F5576BDD1E3BDF
#define DDSC__HOME_KYLONA_WORKSPACE_QBOT_DDS_HELLOWORLDDATA_H_1BAFEBD2278FF078A8F5576BDD1E3BDF

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct std_msgs_msg_dds__String_
{
  char * data;
} std_msgs_msg_dds__String_;

extern const dds_topic_descriptor_t std_msgs_msg_dds__String__desc;

#define std_msgs_msg_dds__String___alloc() \
((std_msgs_msg_dds__String_*) dds_alloc (sizeof (std_msgs_msg_dds__String_)));

#define std_msgs_msg_dds__String__free(d,o) \
dds_sample_free ((d), &std_msgs_msg_dds__String__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_KYLONA_WORKSPACE_QBOT_DDS_HELLOWORLDDATA_H_1BAFEBD2278FF078A8F5576BDD1E3BDF */
